{% macro main(rule) %}
# China Area Network
# > 360
DOMAIN-SUFFIX,qhres.com,{{ rule }}
DOMAIN-SUFFIX,qhimg.com,{{ rule }}
# > Alibaba
# USER-AGENT,%E4%BC%98%E9%85%B7*
DOMAIN-SUFFIX,alibaba.com,{{ rule }}
DOMAIN-SUFFIX,alibabausercontent.com,{{ rule }}
DOMAIN-SUFFIX,alicdn.com,{{ rule }}
DOMAIN-SUFFIX,alikunlun.com,{{ rule }}
DOMAIN-SUFFIX,alipay.com,{{ rule }}
DOMAIN-SUFFIX,amap.com,{{ rule }}
DOMAIN-SUFFIX,autonavi.com,{{ rule }}
DOMAIN-SUFFIX,dingtalk.com,{{ rule }}
DOMAIN-SUFFIX,mxhichina.com,{{ rule }}
DOMAIN-SUFFIX,soku.com,{{ rule }}
DOMAIN-SUFFIX,taobao.com,{{ rule }}
DOMAIN-SUFFIX,tmall.com,{{ rule }}
DOMAIN-SUFFIX,tmall.hk,{{ rule }}
DOMAIN-SUFFIX,ykimg.com,{{ rule }}
DOMAIN-SUFFIX,youku.com,{{ rule }}
DOMAIN-SUFFIX,xiami.com,{{ rule }}
DOMAIN-SUFFIX,xiami.net,{{ rule }}
# > Apple
DOMAIN-SUFFIX,aaplimg.com,{{ rule }}
DOMAIN-SUFFIX,apple.co,{{ rule }}
DOMAIN-SUFFIX,apple.com,{{ rule }}
DOMAIN-SUFFIX,apple-cloudkit.com,{{ rule }}
DOMAIN-SUFFIX,appstore.com,{{ rule }}
DOMAIN-SUFFIX,cdn-apple.com,{{ rule }}
DOMAIN-SUFFIX,icloud.com,{{ rule }}
DOMAIN-SUFFIX,icloud-content.com,{{ rule }}
DOMAIN-SUFFIX,me.com,{{ rule }}
DOMAIN-SUFFIX,mzstatic.com,{{ rule }}
# DOMAIN-KEYWORD,apple.com.akadns.net
# DOMAIN-KEYWORD,icloud.com.akadns.net
# > Baidu
DOMAIN-SUFFIX,baidu.com,{{ rule }}
DOMAIN-SUFFIX,baidubcr.com,{{ rule }}
DOMAIN-SUFFIX,baidupan.com,{{ rule }}
DOMAIN-SUFFIX,baidupcs.com,{{ rule }}
DOMAIN-SUFFIX,bdimg.com,{{ rule }}
DOMAIN-SUFFIX,bdstatic.com,{{ rule }}
DOMAIN-SUFFIX,yunjiasu-cdn.net,{{ rule }}
# > Battle
DOMAIN-SUFFIX,battle.net,{{ rule }}
DOMAIN-SUFFIX,blizzard.com,{{ rule }}
# > bilibili
DOMAIN-SUFFIX,acgvideo.com,{{ rule }}
DOMAIN-SUFFIX,biliapi.com,{{ rule }}
DOMAIN-SUFFIX,biliapi.net,{{ rule }}
DOMAIN-SUFFIX,bilibili.com,{{ rule }}
DOMAIN-SUFFIX,bilibili.tv,{{ rule }}
DOMAIN-SUFFIX,hdslb.com,{{ rule }}
# > ByteDance
DOMAIN-SUFFIX,feiliao.com,{{ rule }}
DOMAIN-SUFFIX,pstatp.com,{{ rule }}
DOMAIN-SUFFIX,snssdk.com,{{ rule }}
DOMAIN-SUFFIX,iesdouyin.com,{{ rule }}
DOMAIN-SUFFIX,toutiao.com,{{ rule }}
# > CCTV
DOMAIN-SUFFIX,cctv.com,{{ rule }}
DOMAIN-SUFFIX,cctvpic.com,{{ rule }}
DOMAIN-SUFFIX,livechina.com,{{ rule }}
# > ChinaTelecom
DOMAIN-SUFFIX,21cn.com,{{ rule }}
# > DiDi
DOMAIN-SUFFIX,didialift.com,{{ rule }}
DOMAIN-SUFFIX,didiglobal.com,{{ rule }}
DOMAIN-SUFFIX,udache.com,{{ rule }}
# > HunanTV
DOMAIN-SUFFIX,hitv.com,{{ rule }}
DOMAIN-SUFFIX,mgtv.com,{{ rule }}
# > iQiyi
DOMAIN-SUFFIX,iqiyi.com,{{ rule }}
DOMAIN-SUFFIX,iqiyipic.com,{{ rule }}
DOMAIN-SUFFIX,71.am,{{ rule }}
# > JD
DOMAIN-SUFFIX,jd.com,{{ rule }}
DOMAIN-SUFFIX,jd.hk,{{ rule }}
DOMAIN-SUFFIX,jdpay.com,{{ rule }}
DOMAIN-SUFFIX,360buyimg.com,{{ rule }}
# > Kingsoft
DOMAIN-SUFFIX,iciba.com,{{ rule }}
DOMAIN-SUFFIX,ksosoft.com,{{ rule }}
# > Meitu
DOMAIN-SUFFIX,meitu.com,{{ rule }}
DOMAIN-SUFFIX,meitudata.com,{{ rule }}
DOMAIN-SUFFIX,meitustat.com,{{ rule }}
DOMAIN-SUFFIX,meipai.com,{{ rule }}
# > Meituan
DOMAIN-SUFFIX,dianping.com,{{ rule }}
DOMAIN-SUFFIX,dpfile.com,{{ rule }}
DOMAIN-SUFFIX,meituan.com,{{ rule }}
DOMAIN-SUFFIX,meituan.net,{{ rule }}
# > MI
DOMAIN-SUFFIX,duokan.com,{{ rule }}
DOMAIN-SUFFIX,mi.com,{{ rule }}
DOMAIN-SUFFIX,mi-img.com,{{ rule }}
DOMAIN-SUFFIX,miui.com,{{ rule }}
DOMAIN-SUFFIX,miwifi.com,{{ rule }}
DOMAIN-SUFFIX,xiaomi.com,{{ rule }}
DOMAIN-SUFFIX,xiaomi.net,{{ rule }}
# > Microsoft
# DOMAIN-SUFFIX,microsoft.com
# DOMAIN-SUFFIX,msecnd.net
# DOMAIN-SUFFIX,office.com
# DOMAIN-SUFFIX,office365.com
# DOMAIN-SUFFIX,s-microsoft.com
# DOMAIN-SUFFIX,windows.com
DOMAIN-SUFFIX,visualstudio.com,{{ rule }}
# >> Microsoft Software Download
# DOMAIN,software-download.microsoft.com
# DOMAIN-KEYWORD,-microsoft-com.akamaized.net
# >> OneDrive
# DOMAIN-SUFFIX,1drv.com
# DOMAIN-SUFFIX,storage.live.com
# >> Outlook
DOMAIN-SUFFIX,hotmail.com,{{ rule }}
DOMAIN-SUFFIX,outlook.com,{{ rule }}
DOMAIN,outlook.office365.com,{{ rule }}
DOMAIN,smtp.office365.com,{{ rule }}
# >> Windows Server Update Services
DOMAIN-SUFFIX,dl.delivery.mp.microsoft.com,{{ rule }}
DOMAIN-SUFFIX,update.microsoft.com,{{ rule }}
DOMAIN-SUFFIX,windowsupdate.com,{{ rule }}
DOMAIN-SUFFIX,windowsupdate.microsoft.com,{{ rule }}
DOMAIN,download.microsoft.com,{{ rule }}
DOMAIN,wustat.windows.com,{{ rule }}
DOMAIN,ntservicepack.microsoft.com,{{ rule }}
# > NetEase
# USER-AGENT,NeteaseMusic*
# USER-AGENT,%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90*
DOMAIN-SUFFIX,163.com,{{ rule }}
DOMAIN-SUFFIX,126.com,{{ rule }}
DOMAIN-SUFFIX,126.net,{{ rule }}
DOMAIN-SUFFIX,127.net,{{ rule }}
DOMAIN-SUFFIX,163yun.com,{{ rule }}
DOMAIN-SUFFIX,lofter.com,{{ rule }}
DOMAIN-SUFFIX,netease.com,{{ rule }}
DOMAIN-SUFFIX,ydstatic.com,{{ rule }}
DOMAIN-SUFFIX,youdao.com,{{ rule }}
# > PayPal
# USER-AGENT,PayPal*
DOMAIN-SUFFIX,paypal.com,{{ rule }}
DOMAIN-SUFFIX,paypal.me,{{ rule }}
DOMAIN-SUFFIX,paypalobjects.com,{{ rule }}
# > Sina
DOMAIN-SUFFIX,sina.com,{{ rule }}
DOMAIN-SUFFIX,weibo.com,{{ rule }}
DOMAIN-SUFFIX,weibocdn.com,{{ rule }}
# > Sohu
DOMAIN-SUFFIX,sohu.com,{{ rule }}
DOMAIN-SUFFIX,sohucs.com,{{ rule }}
DOMAIN-SUFFIX,sohu-inc.com,{{ rule }}
DOMAIN-SUFFIX,v-56.com,{{ rule }}
# > Sogo
DOMAIN-SUFFIX,sogo.com,{{ rule }}
DOMAIN-SUFFIX,sogou.com,{{ rule }}
DOMAIN-SUFFIX,sogoucdn.com,{{ rule }}
# > Tencent
# USER-AGENT,MicroMessenger*
# USER-AGENT,WeChat*
# USER-AGENT,%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1*
DOMAIN-SUFFIX,gtimg.com,{{ rule }}
DOMAIN-SUFFIX,idqqimg.com,{{ rule }}
DOMAIN-SUFFIX,igamecj.com,{{ rule }}
DOMAIN-SUFFIX,myapp.com,{{ rule }}
DOMAIN-SUFFIX,myqcloud.com,{{ rule }}
DOMAIN-SUFFIX,qq.com,{{ rule }}
DOMAIN-SUFFIX,qqmail.com,{{ rule }}
DOMAIN-SUFFIX,servicewechat.com,{{ rule }}
DOMAIN-SUFFIX,tencent.com,{{ rule }}
DOMAIN-SUFFIX,tencent-cloud.com,{{ rule }}
DOMAIN-SUFFIX,tencent-cloud.net,{{ rule }}
DOMAIN-SUFFIX,tenpay.com,{{ rule }}
DOMAIN-SUFFIX,wechat.com,{{ rule }}
DOMAIN,file-igamecj.akamaized.net,{{ rule }}
IP-CIDR,182.254.116.0/24,{{ rule }},no-resolve
IP-CIDR,203.205.254.0/23,{{ rule }},no-resolve
# > Content Delivery Network
DOMAIN-SUFFIX,ccgslb.com,{{ rule }}
DOMAIN-SUFFIX,ccgslb.net,{{ rule }}
DOMAIN-SUFFIX,chinanetcenter.com,{{ rule }}
DOMAIN-SUFFIX,meixincdn.com,{{ rule }}
DOMAIN-SUFFIX,ourdvs.com,{{ rule }}
DOMAIN-SUFFIX,staticdn.net,{{ rule }}
DOMAIN-SUFFIX,wangsu.com,{{ rule }}
# > IP Query
DOMAIN-SUFFIX,ipip.net,{{ rule }}
DOMAIN-SUFFIX,ip.la,{{ rule }}
DOMAIN-SUFFIX,ip.sb,{{ rule }}
DOMAIN-SUFFIX,ip-cdn.com,{{ rule }}
DOMAIN-SUFFIX,ipv6-test.com,{{ rule }}
DOMAIN-SUFFIX,myip.la,{{ rule }}
DOMAIN-SUFFIX,test-ipv6.com,{{ rule }}
DOMAIN-SUFFIX,whatismyip.com,{{ rule }}
DOMAIN,ip.istatmenus.app,{{ rule }}
DOMAIN,sms.imagetasks.com,{{ rule }}
# > Speed Test
# DOMAIN-SUFFIX,speedtest.net
DOMAIN-SUFFIX,netspeedtestmaster.com,{{ rule }}
DOMAIN,speedtest.macpaw.com,{{ rule }}
# > Private Tracker
DOMAIN-SUFFIX,acg.rip,{{ rule }}
DOMAIN-SUFFIX,animebytes.tv,{{ rule }}
DOMAIN-SUFFIX,awesome-hd.me,{{ rule }}
DOMAIN-SUFFIX,broadcasthe.net,{{ rule }}
DOMAIN-SUFFIX,chdbits.co,{{ rule }}
DOMAIN-SUFFIX,classix-unlimited.co.uk,{{ rule }}
DOMAIN-SUFFIX,comicat.org,{{ rule }}
DOMAIN-SUFFIX,empornium.me,{{ rule }}
DOMAIN-SUFFIX,gazellegames.net,{{ rule }}
DOMAIN-SUFFIX,hdbits.org,{{ rule }}
DOMAIN-SUFFIX,hdchina.org,{{ rule }}
DOMAIN-SUFFIX,hddolby.com,{{ rule }}
DOMAIN-SUFFIX,hdhome.org,{{ rule }}
DOMAIN-SUFFIX,hdsky.me,{{ rule }}
DOMAIN-SUFFIX,icetorrent.org,{{ rule }}
DOMAIN-SUFFIX,jpopsuki.eu,{{ rule }}
DOMAIN-SUFFIX,keepfrds.com,{{ rule }}
DOMAIN-SUFFIX,madsrevolution.net,{{ rule }}
DOMAIN-SUFFIX,morethan.tv,{{ rule }}
DOMAIN-SUFFIX,m-team.cc,{{ rule }}
DOMAIN-SUFFIX,myanonamouse.net,{{ rule }}
DOMAIN-SUFFIX,nanyangpt.com,{{ rule }}
DOMAIN-SUFFIX,ncore.cc,{{ rule }}
DOMAIN-SUFFIX,open.cd,{{ rule }}
DOMAIN-SUFFIX,ourbits.club,{{ rule }}
DOMAIN-SUFFIX,passthepopcorn.me,{{ rule }}
DOMAIN-SUFFIX,privatehd.to,{{ rule }}
DOMAIN-SUFFIX,pterclub.com,{{ rule }}
DOMAIN-SUFFIX,redacted.ch,{{ rule }}
DOMAIN-SUFFIX,springsunday.net,{{ rule }}
DOMAIN-SUFFIX,tjupt.org,{{ rule }}
DOMAIN-SUFFIX,totheglory.im,{{ rule }}
# > Other
DOMAIN-SUFFIX,cn,{{ rule }}
DOMAIN-SUFFIX,115.com,{{ rule }}
DOMAIN-SUFFIX,360in.com,{{ rule }}
DOMAIN-SUFFIX,51ym.me,{{ rule }}
DOMAIN-SUFFIX,8686c.com,{{ rule }}
DOMAIN-SUFFIX,99.com,{{ rule }}
DOMAIN-SUFFIX,abchina.com,{{ rule }}
DOMAIN-SUFFIX,accuweather.com,{{ rule }}
DOMAIN-SUFFIX,agora.io,{{ rule }}
DOMAIN-SUFFIX,aicoinstorge.com,{{ rule }}
DOMAIN-SUFFIX,air-matters.com,{{ rule }}
DOMAIN-SUFFIX,air-matters.io,{{ rule }}
DOMAIN-SUFFIX,aixifan.com,{{ rule }}
DOMAIN-SUFFIX,amd.com,{{ rule }}
DOMAIN-SUFFIX,b612.net,{{ rule }}
DOMAIN-SUFFIX,bdatu.com,{{ rule }}
DOMAIN-SUFFIX,beitaichufang.com,{{ rule }}
DOMAIN-SUFFIX,booking.com,{{ rule }}
DOMAIN-SUFFIX,bstatic.com,{{ rule }}
DOMAIN-SUFFIX,cailianpress.com,{{ rule }}
DOMAIN-SUFFIX,camera360.com,{{ rule }}
DOMAIN-SUFFIX,chaoxing.com,{{ rule }}
DOMAIN-SUFFIX,chaoxing.com,{{ rule }}
DOMAIN-SUFFIX,chinaso.com,{{ rule }}
DOMAIN-SUFFIX,chuimg.com,{{ rule }}
DOMAIN-SUFFIX,chunyu.mobi,{{ rule }}
DOMAIN-SUFFIX,cibntv.net,{{ rule }}
DOMAIN-SUFFIX,cmbchina.com,{{ rule }}
DOMAIN-SUFFIX,cmbimg.com,{{ rule }}
DOMAIN-SUFFIX,coolapk.com,{{ rule }}
DOMAIN-SUFFIX,ctrip.com,{{ rule }}
DOMAIN-SUFFIX,dfcfw.com,{{ rule }}
DOMAIN-SUFFIX,dji.net,{{ rule }}
DOMAIN-SUFFIX,docschina.org,{{ rule }}
DOMAIN-SUFFIX,douban.com,{{ rule }}
DOMAIN-SUFFIX,doubanio.com,{{ rule }}
DOMAIN-SUFFIX,douyu.com,{{ rule }}
DOMAIN-SUFFIX,dxycdn.com,{{ rule }}
DOMAIN-SUFFIX,dytt8.net,{{ rule }}
DOMAIN-SUFFIX,eastmoney.com,{{ rule }}
DOMAIN-SUFFIX,eudic.net,{{ rule }}
DOMAIN-SUFFIX,feng.com,{{ rule }}
DOMAIN-SUFFIX,fengkongcloud.com,{{ rule }}
DOMAIN-SUFFIX,frdic.com,{{ rule }}
DOMAIN-SUFFIX,futu5.com,{{ rule }}
DOMAIN-SUFFIX,futunn.com,{{ rule }}
DOMAIN-SUFFIX,gandi.net,{{ rule }}
DOMAIN-SUFFIX,gcores.com,{{ rule }}
DOMAIN-SUFFIX,geilicdn.com,{{ rule }}
DOMAIN-SUFFIX,getpricetag.com,{{ rule }}
DOMAIN-SUFFIX,gifshow.com,{{ rule }}
DOMAIN-SUFFIX,godic.net,{{ rule }}
DOMAIN-SUFFIX,heweather.net,{{ rule }}
DOMAIN-SUFFIX,hicloud.com,{{ rule }}
DOMAIN-SUFFIX,hongxiu.com,{{ rule }}
DOMAIN-SUFFIX,hostbuf.com,{{ rule }}
DOMAIN-SUFFIX,huxiucdn.com,{{ rule }}
DOMAIN-SUFFIX,huya.com,{{ rule }}
DOMAIN-SUFFIX,ibm.com,{{ rule }}
DOMAIN-SUFFIX,infinitynewtab.com,{{ rule }}
DOMAIN-SUFFIX,ithome.com,{{ rule }}
DOMAIN-SUFFIX,java.com,{{ rule }}
DOMAIN-SUFFIX,jianguoyun.com,{{ rule }}
DOMAIN-SUFFIX,jianshu.com,{{ rule }}
DOMAIN-SUFFIX,jianshu.io,{{ rule }}
DOMAIN-SUFFIX,jidian.im,{{ rule }}
DOMAIN-SUFFIX,kaiyanapp.com,{{ rule }}
DOMAIN-SUFFIX,kaspersky-labs.com,{{ rule }}
DOMAIN-SUFFIX,keepcdn.com,{{ rule }}
DOMAIN-SUFFIX,kkmh.com,{{ rule }}
DOMAIN-SUFFIX,lanzous.com,{{ rule }}
DOMAIN-SUFFIX,luojilab.com,{{ rule }}
DOMAIN-SUFFIX,maoyan.com,{{ rule }}
DOMAIN-SUFFIX,maoyun.tv,{{ rule }}
DOMAIN-SUFFIX,mls-cdn.com,{{ rule }}
DOMAIN-SUFFIX,mobike.com,{{ rule }}
DOMAIN-SUFFIX,moke.com,{{ rule }}
DOMAIN-SUFFIX,mubu.com,{{ rule }}
DOMAIN-SUFFIX,myzaker.com,{{ rule }}
DOMAIN-SUFFIX,nim-lang-cn.org,{{ rule }}
DOMAIN-SUFFIX,ntp.org,{{ rule }}
DOMAIN-SUFFIX,nvidia.com,{{ rule }}
DOMAIN-SUFFIX,oracle.com,{{ rule }}
DOMAIN-SUFFIX,plex.tv,{{ rule }}
DOMAIN-SUFFIX,qidian.com,{{ rule }}
DOMAIN-SUFFIX,qweather.com,{{ rule }}
DOMAIN-SUFFIX,qyer.com,{{ rule }}
DOMAIN-SUFFIX,qyerstatic.com,{{ rule }}
DOMAIN-SUFFIX,raychase.net,{{ rule }}
DOMAIN-SUFFIX,ronghub.com,{{ rule }}
DOMAIN-SUFFIX,ruguoapp.com,{{ rule }}
DOMAIN-SUFFIX,sankuai.com,{{ rule }}
DOMAIN-SUFFIX,scomper.me,{{ rule }}
DOMAIN-SUFFIX,shouqianba.com,{{ rule }}
DOMAIN-SUFFIX,sm.ms,{{ rule }}
DOMAIN-SUFFIX,smzdm.com,{{ rule }}
DOMAIN-SUFFIX,snapdrop.net,{{ rule }}
DOMAIN-SUFFIX,snwx.com,{{ rule }}
DOMAIN-SUFFIX,s-reader.com,{{ rule }}
DOMAIN-SUFFIX,sspai.com,{{ rule }}
DOMAIN-SUFFIX,subhd.tv,{{ rule }}
DOMAIN-SUFFIX,takungpao.com,{{ rule }}
DOMAIN-SUFFIX,teamviewer.com,{{ rule }}
DOMAIN-SUFFIX,tianyancha.com,{{ rule }}
DOMAIN-SUFFIX,tophub.today,{{ rule }}
DOMAIN-SUFFIX,uning.com,{{ rule }}
DOMAIN-SUFFIX,weather.com,{{ rule }}
DOMAIN-SUFFIX,weico.cc,{{ rule }}
DOMAIN-SUFFIX,weidian.com,{{ rule }}
DOMAIN-SUFFIX,xiachufang.com,{{ rule }}
DOMAIN-SUFFIX,xiaoka.tv,{{ rule }}
DOMAIN-SUFFIX,ximalaya.com,{{ rule }}
DOMAIN-SUFFIX,xinhuanet.com,{{ rule }}
DOMAIN-SUFFIX,xmcdn.com,{{ rule }}
DOMAIN-SUFFIX,yangkeduo.com,{{ rule }}
DOMAIN-SUFFIX,yizhibo.com,{{ rule }}
DOMAIN-SUFFIX,zhangzishi.cc,{{ rule }}
DOMAIN-SUFFIX,zhihu.com,{{ rule }}
DOMAIN-SUFFIX,zhihuishu.com,{{ rule }}
DOMAIN-SUFFIX,zhimg.com,{{ rule }}
DOMAIN-SUFFIX,zhuihd.com,{{ rule }}
DOMAIN,download.jetbrains.com,{{ rule }}
DOMAIN,images-cn.ssl-images-amazon.com,{{ rule }}
{% endmacro %}