{% macro main(rule) %}
DOMAIN-SUFFIX,laodiwx.com,{{ rule }}
PROCESS-NAME,kkacceler.exe,{{ rule }}
PROCESS-NAME,kkredirector.exe,{{ rule }}
PROCESS-NAME,kkproxy.exe,{{ rule }}
PROCESS-NAME,ss_privoxy.exe,{{ rule }}
PROCESS-NAME,qbittorrent-nox,{{ rule }}
PROCESS-NAME,qbittorrent,{{ rule }}
PROCESS-NAME,watchtower,{{ rule }}
PROCESS-NAME,Thunder,{{ rule }}
PROCESS-NAME,DownloadService,{{ rule }}
PROCESS-NAME,qBittorrent,{{ rule }}
PROCESS-NAME,Transmission,{{ rule }}
PROCESS-NAME,fdm,{{ rule }}
PROCESS-NAME,aria2c,{{ rule }}
PROCESS-NAME,Folx,{{ rule }}
PROCESS-NAME,NetTransport,{{ rule }}
PROCESS-NAME,uTorrent,{{ rule }}
PROCESS-NAME,WebTorrent,{{ rule }}
PROCESS-NAME,aria2c.exe,{{ rule }}
PROCESS-NAME,BitComet.exe,{{ rule }}
PROCESS-NAME,fdm.exe,{{ rule }}
PROCESS-NAME,NetTransport.exe,{{ rule }}
PROCESS-NAME,qbittorrent.exe,{{ rule }}
PROCESS-NAME,Thunder.exe,{{ rule }}
PROCESS-NAME,ThunderVIP.exe,{{ rule }}
PROCESS-NAME,transmission-daemon.exe,{{ rule }}
PROCESS-NAME,transmission-qt.exe,{{ rule }}
PROCESS-NAME,uTorrent.exe,{{ rule }}
PROCESS-NAME,WebTorrent.exe,{{ rule }}
DST-PORT,8086,DIRECT,{{ rule }}
DST-PORT,7878,DIRECT,{{ rule }}
DST-PORT,8989,DIRECT,{{ rule }}
DST-PORT,9117,DIRECT,{{ rule }}
DST-PORT,5055,DIRECT,{{ rule }}
DST-PORT,32400,DIRECT,{{ rule }}
{% endmacro %}